notifications:
  slack:
    secure: ZuA+A2VVlyspTjgpTH9TZaa4EneFGNr1GsoIK0tAkUmtkebaSle9DM/f9zJ4f7fWWrNsZcQ5cZmPy1lNDdqDV/ISUPAuoviY61K73Bb9vS0P6BvcsGIFWSL/mT3+BPOnPuTmnb8xuIAlAHqiKqf2dofaori6hd83A2/iHN77++kkXaa+pM5dupfH/C2DnbcdUcrmtRMPjpEyy05PZ1imGpvKyxV7QfwOf7x3huRH6LSNA4U5GFbYG24LgbpW/KIpSstNEbOSwwsi/lNGnS+msbGm9ctzohB9mBEcj82HLIZEFqJwY/7A2Xz0oo7mKkdTYx3HmcDTFB6xvCun8eOvH5aB5e7tU4PgZ0x55UdwDO720Sgiu+im/vlhQbjJbzIK8OLf70PhHcXQ6Ow7lfcUsHqmHklzLtlv5dgJtGlp9QCQKJyrkXy3YIxT+zdXzKRs1uMes4GYfEMuUxLDWoMPPqPixMl2PpqwivwfgT+Nx9azZYRteRY0TAMcvPz9xLjv51IFxgj0nRBcGWF9YtaOz/VAngNpx5H72gRzZFK2nFSJg0Sz/MK2tTM90+LCYR5/bPBsJSMOIGnaiIJq2KShMwjJvnc4qB2Q1GE9YJm80K6UOOiiQE+F5+7JZJ7MZcEPNo6359MSDIgY2YBttTGoBpzGT+bpryot5hakU9iR61U=
language: node_js
install:
# project build/setup here
- cd $TRAVIS_BUILD_DIR/ui
- npm install
- npm run dist
#- cd $TRAVIS_BUILD_DIR/server
#- npm install
script:
# run tests here
- cd $TRAVIS_BUILD_DIR/ui
#- cd $TRAVIS_BUILD_DIR/server
sudo: required
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: kyle.linden@appliedis.com
  password:
    secure: TP2yZ0NJhJb1ADrkRpFvdxIpS9ffLxnapXLvvlxQ7AzWXe2fTEn91HHm3nJ0DWKh0utCbhSydx9XSBDjggxym1GnzaiZITVUOBYMn/HYAPv/byQTQi5JgpvlPKaTik6DmhQLWfxGV+ikmNDeUqZioc+kp94wjNiAXy9OS16lvAmyNgFDUmhzwbeP5f8QebmZ7ikWiQDYx5rp/ih6zN2axM8aIHR4IKflQmyF81ujbdlJhQPTQCD48TWn/GP6Sno2ZjEi/14mxNk7MCB+zMXgzaYQejj8iz+A6MFsXt6UIk/Q90O9bFYmvGP7ndTba2KF7Yzi8YigxKEsTDkb4MsvnzCLC6bTPzJwfajn1Mz3hq6AYAf03jlUcy5bfsNmQhmQs5g7LNLid1Xc5+gwI0Z8q9dt1V5XjUl+EBcxULNsFaixkMxBjk/TiQF9jY9WHmFrDLAugtoLDWNJctc38HRP2HikKhnRO0Z3o43hf9MNLuvwqWA/mooinkztMgDcJmZ+8igB7l0HVPHWjJDHMdo286EBGZ6LUFQbNn3ChJSEzcKaiCKVxAhjpcKEC3EUSxptmru/1g7YkEC4aEQBr0+xLsp7hh/32Arlj+i0QJUeHP8heoRULvek20z0E/V1zhO1MFRVr+7nPRwOuObz84y0rvjzjT9aTqNIZi5JklahhlY=
  organization: AIS
  space: development
