notifications:
  slack:
    secure: ZuA+A2VVlyspTjgpTH9TZaa4EneFGNr1GsoIK0tAkUmtkebaSle9DM/f9zJ4f7fWWrNsZcQ5cZmPy1lNDdqDV/ISUPAuoviY61K73Bb9vS0P6BvcsGIFWSL/mT3+BPOnPuTmnb8xuIAlAHqiKqf2dofaori6hd83A2/iHN77++kkXaa+pM5dupfH/C2DnbcdUcrmtRMPjpEyy05PZ1imGpvKyxV7QfwOf7x3huRH6LSNA4U5GFbYG24LgbpW/KIpSstNEbOSwwsi/lNGnS+msbGm9ctzohB9mBEcj82HLIZEFqJwY/7A2Xz0oo7mKkdTYx3HmcDTFB6xvCun8eOvH5aB5e7tU4PgZ0x55UdwDO720Sgiu+im/vlhQbjJbzIK8OLf70PhHcXQ6Ow7lfcUsHqmHklzLtlv5dgJtGlp9QCQKJyrkXy3YIxT+zdXzKRs1uMes4GYfEMuUxLDWoMPPqPixMl2PpqwivwfgT+Nx9azZYRteRY0TAMcvPz9xLjv51IFxgj0nRBcGWF9YtaOz/VAngNpx5H72gRzZFK2nFSJg0Sz/MK2tTM90+LCYR5/bPBsJSMOIGnaiIJq2KShMwjJvnc4qB2Q1GE9YJm80K6UOOiiQE+F5+7JZJ7MZcEPNo6359MSDIgY2YBttTGoBpzGT+bpryot5hakU9iR61U=
language: node_js
node_js:
    - "4.1.1"
install:
- cd $TRAVIS_BUILD_DIR/ui
- npm install
- npm run dist
- cd $TRAVIS_BUILD_DIR/api
- npm install
script:
# tests go here
- cd $TRAVIS_BUILD_DIR/api
- npm test
sudo: required
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: kyle.linden@appliedis.com
  password:
    secure: NCft70M/q8X6i3muGQaP5bSf2/PJ8WnkcoYCxHJEmJFTjtv+OuV4H4aiAR+eMwr+oPFE/2xqibv0QqyjEcKQuvn4OX7hAtvtA8Y6sM1MN7DlQUAIRZG/tu0ysET8WRiCnSSP4L0/NL396E6cVTQR+U0LNXrAmX35YcE5bjCL0PhvyXUqyq+1aj8PUpFcNdFkDwFnRUutzSMEHVXOVnUrj9FxW8ubyMHw+VXUzYWlJpfnw2FoMK6wQE324WsE6fKuR4sr5OqS7iAmb8+iumIJrYFMcsDUj9Ee89KZrjckPuXvR1L9E2eyS8noDmXG0B8m/vKb0Or0GCZz40lvVrt5VyeARtSPOFemJ/vfDNpbuAbuiGRw+SVSHBoKu5+R/8Vuir4C7zlRSSnas06wNaowoQkW/VJVpEnhfUzG5UIuwiGiOirW23xUOStzRdtpHbm7k4tVL7eaekN0Lm1glTmVmCgAGASTgCRVJTfb/ZM8VnV+bkp1p+AiiPnLOawrWHAyBB0Xs51EcpdavLwbF2WKIUWPEyMJekJEH4pDgBv2cK4h4HDq955A85GOST5zAgGWVY78ITkv3sy3wqKzhn/K2XEXkgWNfXBAks/x08vuX4qmmRgpXkXpRAcF/yxNJ0YbYbwWe6BstcoUWursq2SRgmtPBUzTNHsKetG8ASURBUg=
  organization: AIS
  space: development
