FROM nginx:latest
MAINTAINER "Michael Bowman<bowmanmc@gmail.com>"

COPY dist /usr/share/nginx/html
RUN rm -v /etc/nginx/nginx.conf
ADD nginx.conf /etc/nginx/
RUN echo "daemon off;" >> /etc/nginx/nginx.conf
